// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VividboxBlazor.Server.Data;

namespace VividboxBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VividboxBlazor.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HResult")
                        .HasColumnType("int");

                    b.Property<string>("HelpLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HResult = -2146233088,
                            Icon = "book",
                            Name = "Books",
                            Url = "Books"
                        },
                        new
                        {
                            Id = 2,
                            HResult = -2146233088,
                            Icon = "aperture",
                            Name = "Games",
                            Url = "Games"
                        },
                        new
                        {
                            Id = 3,
                            HResult = -2146233088,
                            Icon = "monitor",
                            Name = "Computers",
                            Url = "Computers"
                        });
                });

            modelBuilder.Entity("VividboxBlazor.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 15, DateTimeKind.Local).AddTicks(2352),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Here is where the description goes yada yada yada, It can be long.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/b/bd/H2G2_UK_front_cover.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 19.99m,
                            Price = 9.99m,
                            Title = "The Hitchhikers's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9446),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Half-Life 2, stylized as HλLF-LIFE2, is a science fiction first-person shooter developed and published by Valve Corporation, and released on November 16, 2004,[1] following an extended development period of five years. The game garnered near-unanimous positive reviews and received critical acclaim, winning over 30 Game of the Year awards. It is included in The Orange Box for the Xbox 360, PS3, and PC. It was also included for the Original Xbox on November 17th 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2d/Half-Life_2_Episode_Two_title.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 18.88m,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9474),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Custom build AMD Guardian series Gaming PC.   Featuring the latest AMD Ryzen 5 5600X CPU, nVidia RTX3060 video card, 1TB NVME M.2 SSD, 16GB DDR4 memory.    Best suited for regular gamers with best price/performance ratio.",
                            Image = "https://www.compuworld.com.au/app/webroot/stuff/product_image/productImage_5692650061624521489.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 2572.57m,
                            Price = 2176.79m,
                            Title = "AMD Guardian Gaming PC Ryzen 5 RTX3060 1TB SSD 16G"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9477),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AMD Guardian RTX3070 Ti Ryzen 7 Gaming PC. Nvidia RTX3070 Ti video card, Ryzen 7 5800X CPU, 1TB NVME SSD, 16G Ram, 240mm AIO water cooling.",
                            Image = "https://www.compuworld.com.au/app/webroot/stuff/product_image/productImage_2454617561624413498.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 3973.97m,
                            Price = 3362.59m,
                            Title = "AMD Guardian Gaming PC Ryzen 7 RTX3070 Ti 1TB SSD 16G"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9479),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Devastor RTX3080 AMD Ryzen 7 Gaming PC. Ryzen 7 5800X 8 Core CPU, RTX3080 video card, 1TB NVME SSD, 16GB memory.",
                            Image = "https://www.compuworld.com.au/app/webroot/stuff/product_image/productImage_9626281801626400576.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 4717.57m,
                            Price = 3991.79m,
                            Title = "AMD Devastor Gaming PC RTX3080 Ryzen 7 1TB SSD 16G"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9481),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Devastor RTX3080 Ti Gaming PC. With Intel Core i9 X Series CPU, new RTX3080 Ti video card, 2TB NVME SSD, 16G memory, ARGB All in one 360mm water cooling!",
                            Image = "https://www.compuworld.com.au/app/webroot/stuff/product_image/productImage_2509428591624518566.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 6533.67m,
                            Price = 5528.49m,
                            Title = "Intel Devastor Gaming PC RTX3080 Ti X-Series i9 2TB SSD 16G"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9483),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Half-Life 2, stylized as HλLF-LIFE2, is a science fiction first-person shooter developed and published by Valve Corporation, and released on November 16, 2004,[1] following an extended development period of five years. The game garnered near-unanimous positive reviews and received critical acclaim, winning over 30 Game of the Year awards. It is included in The Orange Box for the Xbox 360, PS3, and PC. It was also included for the Original Xbox on November 17th 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2d/Half-Life_2_Episode_Two_title.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 18.88m,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9488),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Half-Life 2, stylized as HλLF-LIFE2, is a science fiction first-person shooter developed and published by Valve Corporation, and released on November 16, 2004,[1] following an extended development period of five years. The game garnered near-unanimous positive reviews and received critical acclaim, winning over 30 Game of the Year awards. It is included in The Orange Box for the Xbox 360, PS3, and PC. It was also included for the Original Xbox on November 17th 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2d/Half-Life_2_Episode_Two_title.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 18.88m,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9490),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Half-Life 2, stylized as HλLF-LIFE2, is a science fiction first-person shooter developed and published by Valve Corporation, and released on November 16, 2004,[1] following an extended development period of five years. The game garnered near-unanimous positive reviews and received critical acclaim, winning over 30 Game of the Year awards. It is included in The Orange Box for the Xbox 360, PS3, and PC. It was also included for the Original Xbox on November 17th 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2d/Half-Life_2_Episode_Two_title.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 18.88m,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9496),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Half-Life 2, stylized as HλLF-LIFE2, is a science fiction first-person shooter developed and published by Valve Corporation, and released on November 16, 2004,[1] following an extended development period of five years. The game garnered near-unanimous positive reviews and received critical acclaim, winning over 30 Game of the Year awards. It is included in The Orange Box for the Xbox 360, PS3, and PC. It was also included for the Original Xbox on November 17th 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2d/Half-Life_2_Episode_Two_title.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 18.88m,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 9, 3, 11, 59, 33, 16, DateTimeKind.Local).AddTicks(9498),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Half-Life 2, stylized as HλLF-LIFE2, is a science fiction first-person shooter developed and published by Valve Corporation, and released on November 16, 2004,[1] following an extended development period of five years. The game garnered near-unanimous positive reviews and received critical acclaim, winning over 30 Game of the Year awards. It is included in The Orange Box for the Xbox 360, PS3, and PC. It was also included for the Original Xbox on November 17th 2005.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2d/Half-Life_2_Episode_Two_title.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 18.88m,
                            Title = "Half-Life 2"
                        });
                });

            modelBuilder.Entity("VividboxBlazor.Shared.Product", b =>
                {
                    b.HasOne("VividboxBlazor.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
